# ~/.bash_logout: executed by bash(1) when login shell exits.

# Ajout tim
printf -v TODAY '%(%Y-%m-%d)T' -1
history >> "$HOME/history_backups/tim_histo_${TODAY}.log"

# deja présent
# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
