# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

printf -v myDate '%(%Y-%m-%d_%Hh%Mm%S)T' -1
history > "$HOME/history_backups/$myDate.log"

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
