"set font for macvim
set guioptions+=b

set bg=light

" special qos energy {
let s:uname = system("echo -n \"$(uname)\"")
if !v:shell_error && s:uname == "Linux"
else
  set guifont=Monaco:h13
endif
" }
