" be iMproved
set nocompatible
" required!
filetype off

"don't loose this key :)
nnoremap \ ,
let mapleader = ","

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'tpope/vim-fugitive'
Plugin 'godlygeek/tabular'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdcommenter'
Plugin 'ervandew/supertab'
Plugin 'tpope/gem-ctags'
Plugin 'mileszs/ack.vim'
"Plugin 'tsaleh/vim-matchit'
Plugin 'edsono/vim-matchit'
Plugin 'altercation/vim-colors-solarized'

" language specific
Plugin 'tpope/vim-haml'
Plugin 'gudleik/vim-slim'
Plugin 'pangloss/vim-javascript'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-markdown'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ap/vim-css-color'
Plugin 'wting/rust.vim'

" for opening file
Plugin 'scrooloose/nerdtree'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'kien/ctrlp.vim'

" other
Plugin 'wakatime/vim-wakatime'
Plugin 'jayflo/vim-skip'
Plugin 'msanders/snipmate.vim'

syntax enable

set autoread " Automatically reload changes if detected
set encoding=utf8
set history=300

" taken here : https://github.com/thoughtstream/Damian-Conway-s-Vim-Setup/blob/master/.vimrc
"           +--Disable hlsearch while loading viminfo
"           | +--Remember marks for last 50 files
"           | |   +--Remember up to 10000 lines in each register
"           | |   |      +--Remember up to 1MB in each register
"           | |   |      |     +--Remember last 1000 search patterns
"           | |   |      |     |     +---Remember last 1000 commands
"           | |   |      |     |     |
"           v v   v      v     v     v
set viminfo=h,'50,<1000,s1000,/500,:1000

" make uses real tabs
au FileType make set noexpandtab

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru,Guardfile} set ft=ruby

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn,txt} call s:setupWrapping()
function s:setupWrapping()
  set wrap
  set textwidth=0
endfunction

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript
au BufNewFile,BufRead *.hbs set ft=html

" make Python follow PEP8 ( http://www.python.org/dev/peps/pep-0008/ )
au FileType python set softtabstop=4 tabstop=4 shiftwidth=4 textwidth=79

autocmd BufRead,BufNewFile *.scss,*.less setlocal foldmethod=marker foldmarker={,}
autocmd BufRead,BufNewFile *.coffee setlocal foldmethod=indent

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Enable syntastic syntax checking
let g:syntastic_enable_signs=1

let Tlist_Auto_Update=1

command Vimrc tabnew $MYVIMRC
command Gvimrc tabnew $MYGVIMRC

" fast terminal for smoother redrawing
set ttyfast
" Tab completion like bash
"set completeopt+=longest
"tab completion for files
set wildmode=list:longest,full
set cryptmethod=blowfish
set iskeyword+=-
