;;; Generated by https://github.com/editor-bootstrap/emacs-bootstrap

(add-to-list 'load-path (concat user-emacs-directory "elisp"))

(require 'base)
(require 'base-theme)
(require 'base-extensions)

(require 'tim-base)
(require 'ag-config)
(require 'evil-config)

(require 'lang-python)
(require 'lang-ruby)
(require 'lang-go)
(require 'lang-php)
(require 'lang-javascript)
(require 'lang-web)
(require 'lang-c)
